import fs from "node:fs";
import path from "node:path";

import { SANDBOX_KNOB_METADATA } from "../apps/hps-dealengine/lib/sandboxKnobAudit";

type ExtendedKnobMetadata = (typeof SANDBOX_KNOB_METADATA)[keyof typeof SANDBOX_KNOB_METADATA] & {
  surfacedIn?: string | string[];
  notes?: string;
};

const repoRoot = path.resolve(__dirname, "..");

function normalizeSurfacedIn(meta: ExtendedKnobMetadata): string {
  if (Array.isArray(meta.surfacedIn) && meta.surfacedIn.length > 0) {
    return meta.surfacedIn.join(", ");
  }
  if (meta.surfacedIn && typeof meta.surfacedIn === "string") {
    return meta.surfacedIn;
  }
  return "—";
}

function normalizeNotes(meta: ExtendedKnobMetadata): string {
  if (meta.notes && meta.notes.trim().length > 0) {
    return meta.notes.trim();
  }
  return "—";
}

function buildRows() {
  return Object.values(SANDBOX_KNOB_METADATA)
    .map((meta) => {
      const extended = meta as ExtendedKnobMetadata;
      return {
        key: meta.key,
        recommendedAction: meta.recommendedAction,
        surfacedIn: normalizeSurfacedIn(extended),
        notes: normalizeNotes(extended),
      };
    })
    .sort((a, b) => a.key.localeCompare(b.key));
}

function computeTotals(rows: ReturnType<typeof buildRows>) {
  return rows.reduce(
    (acc, row) => {
      acc.total += 1;
      if (row.recommendedAction === "KEEP") acc.keep += 1;
      if (row.recommendedAction === "DROP_BACKLOG") acc.dropBacklog += 1;
      return acc;
    },
    { total: 0, keep: 0, dropBacklog: 0 },
  );
}

function renderMarkdown(rows: ReturnType<typeof buildRows>) {
  const totals = computeTotals(rows);
  const lines = [
    "# Sandbox Knobs Audit v1",
    "",
    `Total knobs: ${totals.total}`,
    `KEEP: ${totals.keep}`,
    `DROP_BACKLOG: ${totals.dropBacklog}`,
    "",
    "| Key | Recommended Action | Surfaced In | Notes |",
    "| --- | --- | --- | --- |",
    ...rows.map(
      (row) =>
        `| ${row.key} | ${row.recommendedAction} | ${row.surfacedIn} | ${row.notes} |`,
    ),
    "",
    "Generated by `scripts/generate-knobs-audit-v1.ts`.",
    "",
  ];

  return lines.join("\n");
}

function writeAuditDoc(markdown: string) {
  const outputPath = path.join(repoRoot, "docs/knobs-audit-v1.md");
  fs.writeFileSync(outputPath, markdown, "utf8");
}

function main() {
  const rows = buildRows();
  const markdown = renderMarkdown(rows);
  writeAuditDoc(markdown);
}

main();
