-- Migration: Soft-delete DROP_BACKLOG knobs from sandbox_settings
-- Phase: 7 Slice A - Schema Cleanup
-- Date: 2026-01-06
-- Rollback: Restore from archived_knobs column

-- Step 1: Create backup table (safety net)
CREATE TABLE IF NOT EXISTS sandbox_settings_backup_20260106 AS
SELECT * FROM sandbox_settings;

-- Step 2: Add archived_knobs column if not exists
ALTER TABLE sandbox_settings
ADD COLUMN IF NOT EXISTS archived_knobs JSONB DEFAULT '{}';

-- Step 3: Archive and remove DROP_BACKLOG knobs
UPDATE sandbox_settings
SET
  archived_knobs = jsonb_build_object(
    'archived_at', now(),
    'reason', 'DROP_BACKLOG cleanup Phase 7 Slice A',
    'version', '2.0',
    'values', (
      SELECT COALESCE(jsonb_object_agg(key, value), '{}'::jsonb)
      FROM jsonb_each(config)
      WHERE key IN (
        'actual365PayoffDayCountConvention',
        'aivAsisModelingRetailRepairFrictionMethod',
        'aivSoftMaxCompsAgeDays',
        'aivSoftMinComps',
        'aivSoftMinCompsRadius',
        'allocationToggleBuyerVsSeller',
        'assignmentFeeVipOverrideMaxArvPercentage',
        'assignmentFeeVipOverrideMinArvPercentage',
        'auctionUrgencyMarginAdderPolicy',
        'auctionUrgencyTrpMultiplierPolicy',
        'buyerCostsAllocationDefaultSellerPays',
        'buyerCostsTitleQuoteEvidenceRequirement',
        'buyerSegmentationFlipperMaxMoi',
        'buyerSegmentationLandlordMinGrossYield',
        'buyerSegmentationLandlordMinMoi',
        'buyerSegmentationWholetailMinYearBuilt',
        'buyerTargetMarginFlipMoiBands',
        'buyerTargetMarginMoiTierAdjusters',
        'buyerTargetMarginWholetailFastZip',
        'buyerTargetMarginWholetailNeutralZip',
        'buyerTargetMarginWholetailRangePolicy',
        'buyerTargetMarginWholetailSlowZip',
        'ceilingSelectionConservativeUsesMin',
        'ceilingSelectionHighestEligibleInBase',
        'ceilingSelectionPostureControls',
        'concessionsLadderStep1',
        'concessionsLadderStep2',
        'concessionsLadderStep3',
        'condoSirsMilestoneFlag',
        'counterOfferDefaultIncrement',
        'daysToMoneyRollForwardRule',
        'deedTaxAllocationBuyerSellerSplitToggle',
        'defaultDaysToCashClose',
        'dispositionRecommendationListMlsMinDomZip',
        'dispositionRecommendationListMlsMinDtm',
        'dispositionRecommendationListMlsMinMoi',
        'dispositionRecommendationLogicDtmThresholds',
        'domHardMax',
        'domHardMin',
        'domSoftMaxWarning',
        'domSoftMinWarning',
        'doubleCloseAtoBClosingCostCategories',
        'doubleCloseBtoCClosingCostCategories',
        'doubleCloseFundingPointsPercentage',
        'doubleCloseHoldDaysCalculationMethod',
        'emdPolicyEarnestMoneyStructure',
        'emdRefundabilityConditionsGate',
        'emdTimelineDaysDeadlinePolicy',
        'hoaEstoppelFeeCapPolicy',
        'hoaRushTransferFeePolicy',
        'hoaStatusEvidenceRequiredDocs',
        'insuranceBindabilityEvidence',
        'insuranceCarrierEligibilitySourcesCitizens',
        'interestDayCountBasisDefault',
        'investorBenchmarkModelPostureSelectionMode',
        'investorFloorCompositionComponentsToggle',
        'listingCostModelSellerCostLineItems',
        'maoCalculationMethodArvAivMultiplierSelection',
        'maoNegotiationBandwidthAdjustmentRange',
        'marketLiquidityInputs',
        'marketPriceTieringBracketBreakpointSource',
        'moiHardMax',
        'moiHardMin',
        'moiSoftMaxWarning',
        'moiSoftMinWarning',
        'negotiationBufferPercentage',
        'paceAssessmentHandlingPayoffRequirementPolicy',
        'paceDetectionSourceTaxBillNonAdValoremSelector',
        'perDiemAccrualInputsSeniorJuniorsUsdDay',
        'postureDefaultMode',
        'priceTieringSourceZipPriceBracketsData',
        'projectReviewEvidence',
        'proofOfInsuranceBindableQuoteRequirement',
        'providerSelectorCountyOfficialRecords',
        'providerSelectorMlsCompsDataSource',
        'providerSelectorZipMetrics',
        'repairsContingencyBidsMissing',
        'repairsContingencyHeavyScope',
        'repairsContingencyLightScope',
        'repairsContingencyMediumScope',
        'repairsEvidenceBidsScopeAttachmentRequirement',
        'repairsHardMin',
        'repairsStructuralClassGateFema50Rule',
        'respectFloorCompositionInvestorFloorVsPayoff',
        'respectFloorFormulaComponentSelector',
        'retailListingCostPercentage',
        'retailMakeReadyPerRepairClass',
        'retailRepairFrictionPercentage',
        'rightOfFirstRefusalBoardApprovalWindowDaysInput',
        'secondaryAppraisalRequirementFha',
        'sellerConcessionsCreditsHandlingPolicy',
        'sellerNetRetailMakeReadyInputs',
        'seniorPerDiemHardMax',
        'seniorPerDiemHardMin',
        'seniorPerDiemSoftMaxImpliedApr',
        'seniorPrincipalHardMax',
        'seniorPrincipalHardMin',
        'seniorPrincipalSoftMaxVsArvPercentage',
        'solarLeaseUcc1GateClearanceRequirement',
        'sourcesEvidenceTitleQuotePdfItemizationRequirement',
        'speedBandsSlowMinDom',
        'speedBandsSlowMinMoi',
        'spreadPresentationBorderlineBandHandlingPolicy',
        'titleQuoteAttachmentRequiredForPublishing',
        'transactionalFundingPointsDoubleCloseFinancingInput',
        'ucc1SearchSourceSelectorCountyStateRegistry',
        'ucc1TerminationSubordinationClosingConditionRequirement',
        'uninsurableAdderFlipMarginPercentage',
        'wholesaleFeeModeAssignmentVsDoubleCloseSelection',
        'wholetailMarginPolicyByZipSpeedBand',
        'wholetailRetailMakeReadyInputEvidenceDefaultsToggle',
        'zipSpeedBandPostureControlsMarginHoldingAdjusters'
      )
    )
  ),
  config = config - ARRAY[
    'actual365PayoffDayCountConvention',
    'aivAsisModelingRetailRepairFrictionMethod',
    'aivSoftMaxCompsAgeDays',
    'aivSoftMinComps',
    'aivSoftMinCompsRadius',
    'allocationToggleBuyerVsSeller',
    'assignmentFeeVipOverrideMaxArvPercentage',
    'assignmentFeeVipOverrideMinArvPercentage',
    'auctionUrgencyMarginAdderPolicy',
    'auctionUrgencyTrpMultiplierPolicy',
    'buyerCostsAllocationDefaultSellerPays',
    'buyerCostsTitleQuoteEvidenceRequirement',
    'buyerSegmentationFlipperMaxMoi',
    'buyerSegmentationLandlordMinGrossYield',
    'buyerSegmentationLandlordMinMoi',
    'buyerSegmentationWholetailMinYearBuilt',
    'buyerTargetMarginFlipMoiBands',
    'buyerTargetMarginMoiTierAdjusters',
    'buyerTargetMarginWholetailFastZip',
    'buyerTargetMarginWholetailNeutralZip',
    'buyerTargetMarginWholetailRangePolicy',
    'buyerTargetMarginWholetailSlowZip',
    'ceilingSelectionConservativeUsesMin',
    'ceilingSelectionHighestEligibleInBase',
    'ceilingSelectionPostureControls',
    'concessionsLadderStep1',
    'concessionsLadderStep2',
    'concessionsLadderStep3',
    'condoSirsMilestoneFlag',
    'counterOfferDefaultIncrement',
    'daysToMoneyRollForwardRule',
    'deedTaxAllocationBuyerSellerSplitToggle',
    'defaultDaysToCashClose',
    'dispositionRecommendationListMlsMinDomZip',
    'dispositionRecommendationListMlsMinDtm',
    'dispositionRecommendationListMlsMinMoi',
    'dispositionRecommendationLogicDtmThresholds',
    'domHardMax',
    'domHardMin',
    'domSoftMaxWarning',
    'domSoftMinWarning',
    'doubleCloseAtoBClosingCostCategories',
    'doubleCloseBtoCClosingCostCategories',
    'doubleCloseFundingPointsPercentage',
    'doubleCloseHoldDaysCalculationMethod',
    'emdPolicyEarnestMoneyStructure',
    'emdRefundabilityConditionsGate',
    'emdTimelineDaysDeadlinePolicy',
    'hoaEstoppelFeeCapPolicy',
    'hoaRushTransferFeePolicy',
    'hoaStatusEvidenceRequiredDocs',
    'insuranceBindabilityEvidence',
    'insuranceCarrierEligibilitySourcesCitizens',
    'interestDayCountBasisDefault',
    'investorBenchmarkModelPostureSelectionMode',
    'investorFloorCompositionComponentsToggle',
    'listingCostModelSellerCostLineItems',
    'maoCalculationMethodArvAivMultiplierSelection',
    'maoNegotiationBandwidthAdjustmentRange',
    'marketLiquidityInputs',
    'marketPriceTieringBracketBreakpointSource',
    'moiHardMax',
    'moiHardMin',
    'moiSoftMaxWarning',
    'moiSoftMinWarning',
    'negotiationBufferPercentage',
    'paceAssessmentHandlingPayoffRequirementPolicy',
    'paceDetectionSourceTaxBillNonAdValoremSelector',
    'perDiemAccrualInputsSeniorJuniorsUsdDay',
    'postureDefaultMode',
    'priceTieringSourceZipPriceBracketsData',
    'projectReviewEvidence',
    'proofOfInsuranceBindableQuoteRequirement',
    'providerSelectorCountyOfficialRecords',
    'providerSelectorMlsCompsDataSource',
    'providerSelectorZipMetrics',
    'repairsContingencyBidsMissing',
    'repairsContingencyHeavyScope',
    'repairsContingencyLightScope',
    'repairsContingencyMediumScope',
    'repairsEvidenceBidsScopeAttachmentRequirement',
    'repairsHardMin',
    'repairsStructuralClassGateFema50Rule',
    'respectFloorCompositionInvestorFloorVsPayoff',
    'respectFloorFormulaComponentSelector',
    'retailListingCostPercentage',
    'retailMakeReadyPerRepairClass',
    'retailRepairFrictionPercentage',
    'rightOfFirstRefusalBoardApprovalWindowDaysInput',
    'secondaryAppraisalRequirementFha',
    'sellerConcessionsCreditsHandlingPolicy',
    'sellerNetRetailMakeReadyInputs',
    'seniorPerDiemHardMax',
    'seniorPerDiemHardMin',
    'seniorPerDiemSoftMaxImpliedApr',
    'seniorPrincipalHardMax',
    'seniorPrincipalHardMin',
    'seniorPrincipalSoftMaxVsArvPercentage',
    'solarLeaseUcc1GateClearanceRequirement',
    'sourcesEvidenceTitleQuotePdfItemizationRequirement',
    'speedBandsSlowMinDom',
    'speedBandsSlowMinMoi',
    'spreadPresentationBorderlineBandHandlingPolicy',
    'titleQuoteAttachmentRequiredForPublishing',
    'transactionalFundingPointsDoubleCloseFinancingInput',
    'ucc1SearchSourceSelectorCountyStateRegistry',
    'ucc1TerminationSubordinationClosingConditionRequirement',
    'uninsurableAdderFlipMarginPercentage',
    'wholesaleFeeModeAssignmentVsDoubleCloseSelection',
    'wholetailMarginPolicyByZipSpeedBand',
    'wholetailRetailMakeReadyInputEvidenceDefaultsToggle',
    'zipSpeedBandPostureControlsMarginHoldingAdjusters'
  ]
WHERE config IS NOT NULL;

-- Step 4: Add audit comment
COMMENT ON COLUMN sandbox_settings.archived_knobs IS
  'Archived DROP_BACKLOG knobs from Phase 7 Slice A cleanup (2026-01-06). Preserve for 90 days before hard delete.';

-- Step 5: Create index for rollback queries
CREATE INDEX IF NOT EXISTS idx_sandbox_settings_archived
ON sandbox_settings USING GIN (archived_knobs)
WHERE archived_knobs != '{}'::jsonb;
